name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: solana-vanity-wallet
            asset_name: solana-vanity-wallet-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: solana-vanity-wallet.exe
            asset_name: solana-vanity-wallet-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: solana-vanity-wallet
            asset_name: solana-vanity-wallet-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: solana-vanity-wallet
            asset_name: solana-vanity-wallet-macos-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
